{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "794b07f3-0a79-4bde-8aed-d88df6ac749e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "326\n",
      "93.01447283300513\n"
     ]
    }
   ],
   "source": [
    "import itertools\n",
    "import math\n",
    "from scipy.stats import poisson\n",
    "import pandas as pd\n",
    "import math as mt\n",
    "import numpy as np\n",
    "import time\n",
    "debut = time.perf_counter()\n",
    "def intensite_implication(n_x, n_y, n_xy, n):\n",
    "    lamb = n_x * (n - n_y) / n\n",
    "    if n_y == n:\n",
    "        return 0\n",
    "    else:\n",
    "        phi = 1 - poisson.cdf(n_xy, lamb)\n",
    "        return phi\n",
    "\n",
    "def matrice_implication(fichier_csv):\n",
    "    #df = pd.read_csv(fichier_csv).astype(int)\n",
    "    df = pd.read_csv(fichier_csv)\n",
    "    n = len(df)\n",
    "    attributs = df.columns\n",
    "    taille = len(attributs)\n",
    "    \n",
    "    matrice = pd.DataFrame(np.zeros((taille, taille)), index=attributs, columns=attributs)\n",
    "\n",
    "    for i, x in enumerate(attributs):\n",
    "        for j, y in enumerate(attributs):\n",
    "            n_x = df[x].sum()\n",
    "            n_y = df[y].sum()\n",
    "            n_xy = ((df[x] == 1) & (df[y] == 0)).sum()\n",
    "            phi = intensite_implication(n_x, n_y, n_xy, n)\n",
    "            matrice.iloc[i, j] = phi\n",
    "    return matrice\n",
    "\n",
    "def cohesion_2(p):\n",
    "    if p < 0.5 or p <= 0 or p >= 1:\n",
    "        return 0\n",
    "    elif p == 1:\n",
    "        return 1\n",
    "    else:\n",
    "        try:\n",
    "            H = -p * math.log2(p) - (1 - p) * math.log2(1 - p)\n",
    "            return (1 - H**2)**0.5\n",
    "        except ValueError:\n",
    "            return 0  \n",
    "\n",
    "def cohesion(C, matrice):\n",
    "    if len(C) == 1:\n",
    "        return 1\n",
    "    r = len(C)\n",
    "    produit = 1\n",
    "    liste = list(C)\n",
    "    for i in range(r):\n",
    "        for j in range(i + 1, r):\n",
    "            a, b = liste[i], liste[j]\n",
    "            produit *= cohesion_2(matrice.loc[a, b])\n",
    "    return produit ** (2 / (r * (r - 1)))   \n",
    "mat = matrice_implication('simulation_19.csv') \n",
    "E = mat.index\n",
    "h = []\n",
    "\n",
    "for i in E:\n",
    "    h.append([i])\n",
    "classes = h.copy()\n",
    "m=1\n",
    "while m>0:\n",
    "    candidat = []\n",
    "    for i in classes:\n",
    "        for j in classes:\n",
    "            if set(i)&set(j)==set([]):\n",
    "                candidat.append(i+j)\n",
    "        \n",
    "    maxi = 0\n",
    "    for clas in candidat :\n",
    "        if cohesion(clas,mat)>maxi:\n",
    "            maxi = cohesion(clas,mat)\n",
    "            meilleur_clas = clas\n",
    "    h.append(meilleur_clas)\n",
    "    classes.append(meilleur_clas)\n",
    "    for a in classes:\n",
    "        for b in classes:\n",
    "            if a + b == meilleur_clas:\n",
    "                if a in classes:\n",
    "                    classes.remove(a)\n",
    "                if b in classes and b != a:\n",
    "                    classes.remove(b)\n",
    "    m = maxi\n",
    "#for s in h:\n",
    "#    print(s)\n",
    "print(len(h))\n",
    "\n",
    "fin = time.perf_counter()\n",
    "t = fin - debut\n",
    "print(t)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "befc76f9-045f-4d2b-95dc-204c031e3126",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
